### ISSUE TITLE
MinGW Ruby 2.2 & 2.3 - install old devkit?

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/setup-ruby#2]
@eregon

1. Actions should be adding a MSYS2 installation to the Windows image soon.  Reminder - MSYS2 is the build system for MinGW Rubies 2.4 and later.  The code should be fine with that change, some can be removed later.

2. MinGW Rubies 2.2 & 2.3 use a build system based on MSYS.  The current code in setup-ruby does not install it.  Many items will compile with it, but some won't, and it doesn't match what a normal install is probably using.  If CI isn't installing any extension gems or compiling, obvious it's not needed.  I'm installing it in setup-ruby-pkgs, it seems to take 8 or more seconds.  The question is - should setup-ruby install it, and if not, it should probably be mentioned in the README.

3. I'd still like the function export mentioned previously.  The code in setup-ruby is stable, but every time any version changes (like JRuby, etc), I need to update it.  I tried to use it without the export; it won't work due to `run()` being async...

Hope things are well, Greg

**Comment by eregon** [comment]
1) Good news!
2) I think it'd make sense to move that logic to setup-ruby, if it isn't too complicated. That way setup-ruby always provides a Ruby which can install C extensions (and I think it's kind of OK to be slower on old Ruby versions on Windows).
3) OK, fair enough, I think I get your point better now, it's quite a bit more concise when needing `setup-ruby-pkgs`. Could you create a PR for that? What I'd like though is to show both ways in https://github.com/MSP-Greg/setup-ruby-pkgs/blob/master/README.md so people can choose what they like best (explicit vs concise).

**Comment by MSP-Greg** [comment]
> Good news!

Yeah, but it's kept me busy.  I think we're ok, but I haven't looked at 'actions-ruby', and that's still in use, although I want people to move to setup-ruby-pkgs.

> I think it'd make sense to move that logic to setup-ruby

Good.  Some things will compile on MSYS2, and I can't remember where I ran into problem.  It might have been the C++ code in EventMachine?  Either way, it would probably be better to move it, as it's less support for us.

> I think I get your point better now

Thank you.  I've been working on the README, with a separate doc for Windows info.  I've changed some repo's CI from my actions to setup-ruby as parts of the Windows logic has moved into it.  I have no intention of describing how it's used in setup-ruby-pkgs, or, I don't think the fact some functions are exported is a concern for anyone or something that should be supported.

I look at setup-ruby and setup-ruby-pkgs as a complimentary pair.  One suits most needs, the other allows concise code for control of issues affecting some extension gems/repos on Windows or cross-platform CI.

FYI, I haven't considered setup-ruby-pkgs as released for public use yet, between all the changes I've been making and the MSYS2 changes in Actions.  I thought getting it working well in the repos I work with and the stdlib extension repos (if they'll use it) would be a good way to determine the functionality it should have.  It's also reminded me of some of the edge cases in Windows.

I'll start work on the PR's.  The export one is nothing, the MSYS devkit one is a little bit more...

**Comment by MSP-Greg** [comment]
@eregon

Re pkgs, I just switched over to using setup-ruby instead of my fork.  There's two docs:

[READEME](https://github.com/MSP-Greg/setup-ruby-pkgs/blob/master/README.md)

[Ruby and Windows](https://github.com/MSP-Greg/setup-ruby-pkgs/blob/master/Ruby_and_Windows.md)

Feel free to check the README re language about setup-ruby, and both re info and whether they would make sense to a non Windows user.

**Comment by MSP-Greg** [comment]
Yikes.  You add an input, I need to do the same.  Won't miss that again.

For an example workflow using the new matrix:

https://github.com/ruby/psych/blob/f5f9a3694040e87301056ea51f39f0df24d40f2a/.github/workflows/psych.yml

**Comment by eregon** [comment]
The docs look great to me, congrats on 1.0.

Re `input` that was one concern I had about composing actions, but OTOH it shouldn't happen too often.

**Comment by eregon** [comment]
(we can probably close this issue)

**Comment by MSP-Greg** [comment]
> pacman.exe -Qqs ^mingw-w64-x86_64-

Thanks for looking at the docs.  I did my best to try and explain possible Windows issues without going overboard...

Closing.
