### ISSUE TITLE
Bundler, opt-in, opt-out

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/setup-ruby#3]
@eregon

Good day. 

Importantly, I'm not sure what I think should be done with Bundler.  So the below is not Bundler specific.

Since they may not be common terms:

**opt-in:** user must explicitly respond for something to be done
**opt-out:** user must explicitly respond for something **not** to be done

With pkgs (MSP-Greg/setup-ruby-pkgs), I've tried to make any operation that takes time to be opt-in.  Hence, having the `_update_` options in `apt-get:` and `brew:`.

With `bundler: none`, has it become an opt-out situation with Bundler?  Just concerned about existing CI scripts that don't need Bundler, and may be taking longer than previously.

The trade off is that if we think a strong majority of CI will benefit from something, should we make it opt-out...

**Comment by eregon** [comment]
Good question indeed.

I think the vast majority of usages need Bundler (at least some version of it), and it was always provided for setup-ruby, so it would be a breaking change to not provide it anymore.

On MRI installing Bundler seems to take just about 1 or 2 seconds on Ubuntu, so I think it's barely noticeable on build time.
FWIW, TravisCI also provided Bundler, and always installed it at runtime (with RVM).

Do you see it taking more time than that? I think even on Windows it's quite fast to install Bundler.

**Comment by eregon** [comment]
Longer term I'd like to automatically cache `bundle install` if it becomes possible in actions (i.e. we'd need the cache action to be a toolkit package), for convenience. I think that should be the default if there is a Gemfile.

**Comment by eregon** [comment]
On a related note I was thinking to add some time measurements in the output of the action and maybe grouping too so one can still see how much each part takes, even though it's all done by one action.

**Comment by MSP-Greg** [comment]
> On MRI installing Bundler seems to take just about 1 or 2 seconds on Ubuntu

You're right.  Sorry, I guess I just thought it would be longer, but it's not RG.  I checked, and some pkgs jobs took all of 2 seconds to a) download setup-ruby, b) install Ruby, c) install Bundler.  So, never mind, that's surprising how fast it is.

> Longer term I'd like to automatically cache bundle install
i.e. we'd need the cache action to be a toolkit package)

Interesting.  Never thought about it, especially the post hook.  But, see 
https://github.com/actions/cache/blob/f60097cd16988b176c31ed5e2db51d50a8d19a4e/action.yml#L17-L21, specifically the `post:` & `post-if:` items...

> I was thinking to add some time measurements in the output of the action and maybe grouping

Considering I misjudged that, might be helpful.  Conversely, I think if CI is green, most people never even look at the logs.  IOW, any changes we make will mostly be for our own benefit...

I'll try writing a helper function for that.  Show the elapsed time in the line right below the group.

I used groups in the ruby-loco MinGW build:
https://github.com/MSP-Greg/ruby-loco/runs/560625959?check_suite_focus=true#step:7:18

**Comment by eregon** [comment]
> You're right. Sorry, I guess I just thought it would be longer, but it's not RG.

Indeed, updating RubyGems might take a while and I think might significantly make things less stable, so it's something I would really avoid in ruby/setup-ruby.

Re caching, I'm waiting for https://github.com/actions/cache/issues/55, I would like to avoid having to repackage the entire cache action manually.

**Comment by MSP-Greg** [comment]
Re RG, I was only using it for time comparison, wasn't suggesting updating it, etc...

**Comment by MSP-Greg** [comment]
Re groups and elapsed time, I added it to pkgs.  See below CI for the output:

https://github.com/MSP-Greg/setup-ruby-pkgs/runs/561322552

If any of the group descriptions seem unclear, let me know.  You're probably well beyond the 'target user' in terms of your 'Windows Ruby' knowledge.

I originally did a 'Rubyish' function where I passed the code to run.  Bad idea.  Sync functions, etc.

Changed to two functions in [common.js](https://github.com/MSP-Greg/setup-ruby-pkgs/blob/60daef6c26be62d696edbaf6b58cb236da36be99/common.js):

grpSt - parameter is the text, return is the start time.

grpEnd - parameter is the return from grpSt

Works well, and users (also people like me this morning), can see how long any step takes.  Cleans up the log and allows us to make it verbose if we want.

I didn't clean up the log involving setup-ruby yet, as I haven't checked to see if groups can be nested.  I kind of doubt it...

JFYI, I had problems with that server (azure.archive.ubuntu.com) again, but they cleared up (?)

**Comment by eregon** [comment]
Looks good.
I found that actions/core provides start/endGroup: https://github.com/actions/toolkit/tree/master/packages/core#logging

**Comment by eregon** [comment]
Indeed, groups don't nest: https://github.com/ruby/setup-ruby/runs/561907040?check_suite_focus=true

**Comment by eregon** [comment]
Done, for example see output in https://github.com/ruby/setup-ruby/runs/561987650?check_suite_focus=true
I think it looks quite neat.
Small differences are I didn't use colors, and I moved the time output inside the group.
